chmod +x sendBloomJohn.sh
chmod +x sendBloomRichard.sh
chmod +x sendBloomAudrey.sh
chmod +x sendBloomStorm.sh
chmod +x sendBloomHarvis.sh
chmod +x sendBloomMac.sh
chmod +x sendBloomMurphy.sh
chmod +x sendBloomCourage.sh
chmod +x sendBloomRalph.sh
chmod +x sendBloomFirstStorm.sh
chmod +x sendBloomFirstMac.sh
chmod +x sendBloomFirstCourage.sh
chmod +x sendCSVForJoinStorm.sh
chmod +x sendCSVForJoinHarvis.sh
chmod +x sendCSVForJoinMac.sh
chmod +x sendCSVForJoinMurphy.sh
chmod +x sendCSVForJoinCourage.sh
chmod +x sendCSVForJoinRalph.sh
chmod +x tocloudAudrey.sh
chmod +x tocloudRichard.sh
chmod +x tocloudJohn.sh
chmod +x tocloudAudrey2.sh
chmod +x tocloudRichard2.sh
chmod +x tocloudJohn2.sh
chmod +x startAudrey.sh
chmod +x startRichard.sh
chmod +x startJohn.sh
