chmod +x remMac.sh
chmod +x remHarvis.sh
chmod +x remMurphy.sh
chmod +x remStorm.sh
chmod +x remRalph.sh
chmod +x remCourage.sh
chmod +x tocloudJohn.sh
chmod +x tocloudAudrey.sh
chmod +x tocloudRichard.sh
chmod +x stormReply.sh
chmod +x ralphReply.sh
chmod +x macReply.sh
chmod +x murphyReply.sh
chmod +x courageReply.sh
chmod +x harvisReply.sh
chmod +x sendReqStorm.sh
chmod +x sendReqRalph.sh
chmod +x sendReqHarvis.sh
chmod +x sendReqCourage.sh
chmod +x sendReqMac.sh
chmod +x sendReqMurphy.sh
chmod +x sendReqJohn.sh
chmod +x sendReqRichard.sh
chmod +x sendReqAudrey.sh
